siteTitle: Phoebe Askelson
author:
  name: Phoebe Askelson
  twitter: punchemist
bio: >
  Phoebe Askelson is a PhD candidate studying energy transfer and dynamics
  using nonlinear optical spectroscopies at the University of Pennsylvania, under the
  guidance of Professor Jessica Anna.
links:
  - title: Instagram
    icon: instagram
    link: https://instagram.com/phoebe.askelson/
  - title: LinkedIn
    icon: linkedin
    link: https://www.linkedin.com/in/phoebe-askelson-74b94a160/
  - title: Twitter
    icon: twitter
    link: https://twitter.com/punchemist
